SIGN_UP_OPT = 1
SIGN_IN_OPT = 2
LOGIN_OPTS = [SIGN_UP_OPT , SIGN_IN_OPT]

ADD_PASSWORD = 1
RETRIEVE_PASSWORD = 2
RETRIEVE_ALL = 3
QUIT = 4
MAIN_OPTS = [ADD_PASSWORD, RETRIEVE_PASSWORD, RETRIEVE_ALL, QUIT]