SIGN_UP_OPT = str(1)
SIGN_IN_OPT = str(2)
LOGIN_OPTS = [SIGN_UP_OPT, SIGN_IN_OPT]

ADD_LOG_DETAILS = str(1)
EDIT_LOG_DETAILS = str(2)
DELETE_LOG_DETAILS = str(3)
RETRIEVE_LOG_DETAILS = str(4)
CHECK_LOG_DETAILS_LEAKAGE = str(5)
RETRIEVE_ALL_LOG_DETAILS = str(6)
QUIT = str(7)
MAIN_OPTS = [ADD_LOG_DETAILS, EDIT_LOG_DETAILS, DELETE_LOG_DETAILS, RETRIEVE_LOG_DETAILS,
             CHECK_LOG_DETAILS_LEAKAGE, RETRIEVE_ALL_LOG_DETAILS, QUIT]
