SIGN_UP_OPT = 1
SIGN_IN_OPT = 2
LOGIN_OPTS = [SIGN_UP_OPT, SIGN_IN_OPT]

ADD_LOG_DETAILS = 1
EDIT_LOG_DETAILS = 2
DELETE_LOG_DETAILS = 3
RETRIEVE_LOG_DETAILS = 4
RETRIEVE_ALL_LOG_DETAILS = 5
QUIT = 6
MAIN_OPTS = [ADD_LOG_DETAILS, EDIT_LOG_DETAILS, DELETE_LOG_DETAILS, RETRIEVE_LOG_DETAILS,
             RETRIEVE_ALL_LOG_DETAILS, QUIT]
